### ISSUE TITLE
I downloaded SimpleSynth Code... but

### ISSUE THREAD

**Issue by AcidSatanist** [COx2/JUCE_JAPAN_DEMO#1]
I downloaded SimpleSynth's code, I thought this is so nice
but this project couldn't build and run...
I'm a beginner so I need Right Forms of Codes
So please upload fixed version of SimpleSynth
please

**Comment by COx2** [comment]
Hi,
Unfortunately, I have confirmed that I can build correctly in my development environment.
Sorry for your inconvenience, can you copy and paste the error code output in your compiler?

**Comment by COx2** [comment]
I'm sorry, I found a little problem with my current project.
Apparently, there is a problem related to the difference between the version of JUCE I am using and the latest version.
I have fixed it to build the SimpleSynth with the latest JUCE 5.4.3.
Can you clone the project from the branch shown below and try to build again?
https://github.com/COx2/JUCE_JAPAN_DEMO/tree/for_JUCE5.4.3
